use_frameworks!
platform :ios, '8.0'

target 'NextOfKin_Example' do
  pod 'NextOfKin', :path => '../'

  target 'NextOfKin_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
